name: Update Preview Image

on:
  schedule:
    - cron:  '0 2 * * *'  # Runs every day at 2 AM UTC (which is 9 AM Bangkok time)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download image
      run: |
        curl "https://neoflask.pythonanywhere.com/?username=kritserv&img=flask&main_col=cyan&theme=solarized" -o updated_preview_img/githubstat.svg

    - name: Commit and push if it changed
      run: |
        git config user.name "Neoflask Update-Img Bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated image update: ${timestamp}" || exit 0
        git push
